# Generated by Django 3.2.23 on 2023-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231118_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
