# Generated by Django 3.2.23 on 2023-11-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_school_ofsted'),
        ('profiles', '0004_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.parentprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.school')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
