# Generated by Django 3.2.23 on 2023-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20231120_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Bullying', 'Bullying'), ('Extra-curricular', 'Extra-curricular')], max_length=255),
        ),
    ]
