# Generated by Django 3.2.23 on 2023-11-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=255)),
                ('school_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Sixth Form/College', 'Sixth Form/College')], max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('ofsted', models.CharField(choices=[('Outstanding', 'Outstanding'), ('Good', 'Good'), ('Requires Improvement', 'Requires Improvement'), ('Inadequate', 'Inadequate')], max_length=50)),
            ],
            options={
                'ordering': ['-school_name'],
            },
        ),
    ]
