# Generated by Django 3.2.23 on 2023-11-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_review_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='city',
            new_name='locality_name',
        ),
    ]
