# Generated by Django 3.2.23 on 2023-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_locality_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='overall_rating',
            field=models.CharField(default='This school does not yet have any reviews', max_length=255),
        ),
    ]
