# Generated by Django 3.2.23 on 2023-11-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_review_teaching_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='admin_service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failing'), (2, 'Needs Work'), (3, 'Adequate'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='atmosphere',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failing'), (2, 'Needs Work'), (3, 'Adequate'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='child_happiness',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failing'), (2, 'Needs Work'), (3, 'Adequate'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='teaching_quality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failing'), (2, 'Needs Work'), (3, 'Adequate'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='ofsted',
            field=models.CharField(choices=[(1, 'Grade 1 - Outstanding'), (2, 'Grade 2 - Good'), (3, 'Grade 3 - Requires Improvement'), (4, 'Grade 4 - Inadequate')], max_length=255),
        ),
    ]
