# Generated by Django 3.2.23 on 2023-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20231119_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='admin_service',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Failing'), (2, '2 - Needs Work'), (3, '3 - Adequate'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='atmosphere',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Failing'), (2, '2 - Needs Work'), (3, '3 - Adequate'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='child_happiness',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Failing'), (2, '2 - Needs Work'), (3, '3 - Adequate'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='teaching_quality',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Failing'), (2, '2 - Needs Work'), (3, '3 - Adequate'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='ofsted',
            field=models.IntegerField(choices=[(1, '1 - Outstanding'), (2, '2 - Good'), (3, '3 - Requires Improvement'), (4, '4 - Inadequate')]),
        ),
    ]
