# Generated by Django 3.2.23 on 2023-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_school_ofsted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ofsted',
            field=models.IntegerField(choices=[(1, '1 - Outstanding'), (2, '2 - Good'), (3, '3 - Requires Improvement'), (4, '4 - Inadequate')]),
        ),
    ]
